import type { FastifyInstance } from "fastify"; import { CancellationBodySchema, CancellationSchema, ErrorEnvelopeSchema, MatchSearchResultSchema, MessageBodySchema, MessageListSchema, MessageSchema, PickupStateSchema, PickupStatusBodySchema, ProximityBodySchema, ProximitySchema, TripDetailSchema } from "../../../../../packages/contracts/src"; import { createAuthGuards } from "../membership/auth"; import type { FirebaseTokenVerifier } from "../membership/ports"; import type { MembershipService } from "../membership/service"; import type { TripService } from "./service";
export interface TripRouteDependencies { verifier: FirebaseTokenVerifier; memberships: MembershipService; trips: TripService }
const params = { type: "object", required: ["id"], properties: { id: { type: "string", minLength: 1, maxLength: 128 } } };
export async function registerTripRoutes(app: FastifyInstance, d: TripRouteDependencies) { const auth = createAuthGuards(d.verifier, d.memberships).requireActiveMembership;
app.get<{ Params: { id: string } }>("/v1/trips/:id", { preHandler: auth, schema: { tags: ["trips"], params, response: { 200: TripDetailSchema } } }, async r => d.trips.get(r.identity!, r.params.id));
app.get<{ Params: { id: string } }>("/v1/trips/:id/messages", { preHandler: auth, schema: { tags: ["messages"], params, response: { 200: MessageListSchema } } }, async r => ({ messages: await d.trips.listMessages(r.identity!, r.params.id) }));
app.post<{ Params: { id: string }; Body: { text: string } }>("/v1/trips/:id/messages", { preHandler: auth, schema: { tags: ["messages"], params, body: MessageBodySchema, response: { 201: MessageSchema } } }, async (r, reply) => reply.status(201).send(await d.trips.sendMessage(r.identity!, r.params.id, r.body.text)));
app.post<{ Params: { id: string }; Body: { status: "leaving" | "en_route" | "arrived" | "passenger_ready" | "picked_up" } }>("/v1/trips/:id/status", { preHandler: auth, schema: { tags: ["pickup"], params, body: PickupStatusBodySchema, response: { 200: PickupStateSchema } } }, async r => d.trips.pickup(r.identity!, r.params.id, r.body.status));
app.put<{ Params: { id: string }; Body: { state: "nearby" | "not_nearby" } }>("/v1/trips/:id/proximity", { preHandler: auth, schema: { tags: ["pickup"], params, body: ProximityBodySchema, response: { 200: ProximitySchema, 429: ErrorEnvelopeSchema } } }, async r => d.trips.proximity(r.identity!, r.params.id, r.body.state));
app.delete<{ Params: { id: string } }>("/v1/trips/:id/proximity", { preHandler: auth, schema: { tags: ["pickup"], params } }, async (r, reply) => { await d.trips.stopProximity(r.identity!, r.params.id); return reply.status(204).send(); });
app.post<{ Params: { id: string }; Body: { reason: string } }>("/v1/trips/:id/cancel", { preHandler: auth, schema: { tags: ["recovery"], params, body: CancellationBodySchema, response: { 200: CancellationSchema } } }, async r => d.trips.cancel(r.identity!, r.params.id, r.body.reason));
app.get<{ Params: { id: string } }>("/v1/recoveries/:id/options", { preHandler: auth, schema: { tags: ["recovery"], params, response: { 200: MatchSearchResultSchema, 409: ErrorEnvelopeSchema } } }, async r => d.trips.recovery(r.identity!, r.params.id)); }
