import { randomUUID } from "node:crypto";
import type { MessageView, TripDetail } from "../../../../../packages/contracts/src";
import type { MatchingService } from "../matching/service";
import type { RequestIdentity } from "../membership/domain";
import type { RideStore } from "../ride/ports";
import type { VehicleStore } from "../vehicle/ports";
import type { PlateVault } from "../vehicle/vault";
import { TripError, type MessageRecord, type PickupStateRecord } from "./domain";
import type { TripStore } from "./ports";
const contact = /(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}|[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}|(?:https?:\/\/|www\.)\S+/i;
export class TripService {
  private readonly matching?: MatchingService; private readonly now: () => Date;
  constructor(private readonly trips: TripStore, private readonly rides: RideStore, private readonly vehicles: VehicleStore, private readonly vault: PlateVault, matchingOrNow?: MatchingService | (() => Date), now = () => new Date()) { this.matching = typeof matchingOrNow === "function" ? undefined : matchingOrNow; this.now = typeof matchingOrNow === "function" ? matchingOrNow : now; }
  private async participant(identity: RequestIdentity, id: string, allowCancelled = false) { const ride = await this.rides.get(id); if (!ride || (!allowCancelled && ride.status !== "confirmed") || (allowCancelled && !["confirmed", "cancelled"].includes(ride.status)) || (ride.crewUid !== identity.uid && ride.captainUid !== identity.uid)) throw new TripError("Trip not found.", "TRIP_NOT_FOUND", 404); return ride; }
  async get(identity: RequestIdentity, id: string): Promise<TripDetail> { const ride = await this.participant(identity, id); const vehicle = await this.vehicles.getByOwner(ride.captainUid); if (!vehicle || !ride.confirmedAt) throw new TripError("Trip disclosure is unavailable.", "TRIP_DISCLOSURE_UNAVAILABLE", 409); return { id, status: "confirmed", crewDisplayName: ride.crewDisplayName, captainDisplayName: ride.captainDisplayName, vehicle: { make: vehicle.make, model: vehicle.model, color: vehicle.color, year: vehicle.year, plate: this.vault.decrypt(vehicle.plateCiphertext) }, estimate: { amount: ride.amount, currency: "USD", voluntary: true, paymentProcessed: false }, confirmedAt: ride.confirmedAt.toISOString() }; }
  private message(v: MessageRecord, crewUid: string): MessageView { return { id: v.id, sender: v.senderUid === crewUid ? "crew" : "captain", text: v.text, sentAt: v.sentAt.toISOString() }; }
  async listMessages(identity: RequestIdentity, id: string) { const ride = await this.participant(identity, id); return (await this.trips.listMessages(id, 100)).map(v => this.message(v, ride.crewUid)); }
  async sendMessage(identity: RequestIdentity, id: string, text: string) { const ride = await this.participant(identity, id); const normalized = text.trim(); if (!normalized || contact.test(normalized)) throw new TripError("Messages must be nonempty and cannot include contact details or links.", "CONTACT_DETAILS_NOT_ALLOWED", 400); const now = this.now(); const m = { id: randomUUID(), tripId: id, tenantId: ride.tenantId, senderUid: identity.uid, text: normalized, sentAt: now }; return this.message(await this.trips.saveMessage(m, { id: randomUUID(), recipientUid: identity.uid === ride.crewUid ? ride.captainUid : ride.crewUid, type: "new_message", resourceId: id, createdAt: now }), ride.crewUid); }
  async pickup(identity: RequestIdentity, id: string, status: PickupStateRecord["status"]) { const ride = await this.participant(identity, id); const captainOnly = ["leaving", "en_route", "arrived", "picked_up"]; if (captainOnly.includes(status) && identity.uid !== ride.captainUid) throw new TripError("Only the captain can set that pickup status.", "STATUS_NOT_ALLOWED", 403); if (status === "passenger_ready" && identity.uid !== ride.crewUid) throw new TripError("Only the crew member can mark passenger ready.", "STATUS_NOT_ALLOWED", 403); const current = (await this.trips.getPickupState(id))?.status ?? "confirmed"; const order = ["confirmed", "leaving", "en_route", "nearby", "arrived", "passenger_ready", "picked_up"]; if (order.indexOf(status) < order.indexOf(current) || current === "picked_up") throw new TripError("That pickup transition is not allowed.", "INVALID_TRIP_STATE", 409); const saved = await this.trips.savePickupState({ tripId: id, status, updatedAt: this.now() }); if (status === "picked_up") await this.trips.deleteProximity(id); return { tripId: id, status: saved.status, updatedAt: saved.updatedAt.toISOString() }; }
  async proximity(identity: RequestIdentity, id: string, state: "nearby" | "not_nearby") { await this.participant(identity, id); const now = this.now(); const previous = await this.trips.getProximity(id); if (previous && previous.actorUid === identity.uid && now.getTime() - previous.updatedAt.getTime() < 30_000) throw new TripError("Proximity updates are limited to one every 30 seconds.", "PROXIMITY_RATE_LIMITED", 429); const record = await this.trips.saveProximity({ tripId: id, actorUid: identity.uid, state, updatedAt: now, expiresAt: new Date(now.getTime() + 10 * 60_000) }); if (state === "nearby") await this.trips.savePickupState({ tripId: id, status: "nearby", updatedAt: now }); return { tripId: id, state, expiresAt: record.expiresAt.toISOString() }; }
  async stopProximity(identity: RequestIdentity, id: string) { await this.participant(identity, id, true); await this.trips.deleteProximity(id); }
  async cancel(identity: RequestIdentity, id: string, reason: string) { const ride = await this.participant(identity, id); const now = this.now(); await this.rides.cancel(id, identity.uid, reason, now); await this.trips.deleteProximity(id); await this.trips.savePickupState({ tripId: id, status: "cancelled", updatedAt: now }); return { tripId: id, status: "cancelled" as const, reason, cancelledAt: now.toISOString(), recoveryAvailable: identity.uid === ride.crewUid || identity.uid === ride.captainUid }; }
  async recovery(identity: RequestIdentity, id: string) { const ride = await this.participant(identity, id, true); if (ride.status !== "cancelled" || identity.uid !== ride.crewUid || !this.matching) throw new TripError("Recovery options are unavailable.", "RECOVERY_NOT_AVAILABLE", 409); return this.matching.search(identity, ride.shiftId, ride.leg); }
}
