import { randomUUID } from "node:crypto";
import type { CompletionBody, RatingBody, SafetyReportBody } from "../../../../../packages/contracts/src";
import type { MatchingStore } from "../matching/ports";
import type { RequestIdentity } from "../membership/domain";
import type { MembershipStore } from "../membership/ports";
import type { OperationsService } from "../operations/service";
import type { RideStore } from "../ride/ports";
import { TripError } from "./domain";
import type { TripStore } from "./ports";
export class TrustService { constructor(private readonly store: TripStore, private readonly rides: RideStore, private readonly matches: MatchingStore, private readonly memberships: MembershipStore, private readonly now = () => new Date(), private readonly operations?:OperationsService) {} private async participant(i: RequestIdentity, id: string) { const v = await this.rides.get(id); if (!v || !["confirmed", "cancelled"].includes(v.status) || (v.crewUid !== i.uid && v.captainUid !== i.uid)) throw new TripError("Trip not found.", "TRIP_NOT_FOUND", 404); return v; } async complete(i: RequestIdentity, id: string, b: CompletionBody) { const v = await this.participant(i, id); const now = this.now(); const role = i.uid === v.crewUid ? "crew" : "captain"; const r = await this.store.saveCompletion({ id: `${id}_${i.uid}`, tripId: id, uid: i.uid, tenantId: i.tenantId, role, completed: b.completed, shiftProtected: b.shiftProtected, recordedAt: now }); return { tripId: id, participantRole: role, completed: r.completed, shiftProtected: r.shiftProtected, recordedAt: r.recordedAt.toISOString() }; } async rate(i: RequestIdentity, id: string, b: RatingBody) { const v = await this.participant(i, id); const now = this.now(); await this.store.saveRating({ id: `${id}_${i.uid}`, tripId: id, authorUid: i.uid, subjectUid: i.uid === v.crewUid ? v.captainUid : v.crewUid, tenantId: i.tenantId, punctuality: b.punctuality, communication: b.communication, safetyComfort: b.safetyComfort, respect: b.respect, privateNote: b.privateNote?.trim() || null, recordedAt: now }); return { tripId: id, submitted: true as const, recordedAt: now.toISOString() }; } async block(i: RequestIdentity, uid: string) { if (uid === i.uid) throw new TripError("You cannot block yourself.", "INVALID_BLOCK", 400); const member = await this.memberships.getMembershipForUser(uid); if (!member || member.tenantId !== i.tenantId || member.worksiteId !== i.worksiteId) throw new TripError("User not found.", "USER_NOT_FOUND", 404); const r = await this.matches.block(i.tenantId, i.uid, uid, this.now()); return { id: r.id, blockedUserId: uid, createdAt: r.createdAt.toISOString() }; } async report(i: RequestIdentity, b: SafetyReportBody) { let subjectUid: string | null = null; if (b.tripId) { const v = await this.participant(i, b.tripId); subjectUid = i.uid === v.crewUid ? v.captainUid : v.crewUid; } const now = this.now(); const r = await this.store.saveSafetyReport({ id: randomUUID(), reporterUid: i.uid, tenantId: i.tenantId, worksiteId: i.worksiteId, tripId: b.tripId ?? null, subjectUid, category: b.category, narrative: b.narrative.trim(), status: "open", createdAt: now }); await this.operations?.captureSafetyReport(r); return { id: r.id, status: "open" as const, emergencyMessage: "If anyone is in immediate danger, call 911." as const, createdAt: now.toISOString() }; } }
