import type { FastifyInstance } from "fastify";
import { CommuteProfileBodySchema, CommuteProfileSchema, ErrorEnvelopeSchema, IcsImportBodySchema, RecurringShiftInputSchema, RecurringShiftSchema, ShiftListSchema, type CommuteProfileBody, type RecurringShiftInput } from "../../../../../packages/contracts/src";
import { createAuthGuards } from "../membership/auth"; import type { FirebaseTokenVerifier } from "../membership/ports"; import type { MembershipService } from "../membership/service"; import type { CommuteService } from "./service";
export interface CommuteRouteDependencies { verifier: FirebaseTokenVerifier; memberships: MembershipService; commutes: CommuteService }
export async function registerCommuteRoutes(app: FastifyInstance, d: CommuteRouteDependencies) { const guards = createAuthGuards(d.verifier, d.memberships); const auth = guards.requireActiveMembership;
  app.get("/v1/profile", { preHandler: auth, schema: { tags: ["commute"], response: { 200: CommuteProfileSchema, 401: ErrorEnvelopeSchema, 403: ErrorEnvelopeSchema, 404: ErrorEnvelopeSchema } } }, async (r) => d.commutes.getProfile(r.identity!));
  app.put<{ Body: CommuteProfileBody }>("/v1/profile", { preHandler: auth, schema: { tags: ["commute"], body: CommuteProfileBodySchema, response: { 200: CommuteProfileSchema, 400: ErrorEnvelopeSchema, 401: ErrorEnvelopeSchema, 403: ErrorEnvelopeSchema } } }, async (r) => d.commutes.saveProfile(r.identity!, r.body));
  app.get("/v1/shifts", { preHandler: auth, schema: { tags: ["schedule"], response: { 200: ShiftListSchema, 401: ErrorEnvelopeSchema, 403: ErrorEnvelopeSchema } } }, async (r) => ({ shifts: await d.commutes.listShifts(r.identity!) }));
  app.post<{ Body: RecurringShiftInput }>("/v1/shifts", { preHandler: auth, schema: { tags: ["schedule"], body: RecurringShiftInputSchema, response: { 201: RecurringShiftSchema, 400: ErrorEnvelopeSchema } } }, async (r, reply) => reply.status(201).send(await d.commutes.createManual(r.identity!, r.body)));
  app.post<{ Body: { ics: string } }>("/v1/schedule/ics", { preHandler: auth, schema: { tags: ["schedule"], body: IcsImportBodySchema, response: { 201: ShiftListSchema, 400: ErrorEnvelopeSchema } } }, async (r, reply) => reply.status(201).send({ shifts: await d.commutes.importIcs(r.identity!, r.body.ics) }));
  app.post<{ Params: { id: string } }>("/v1/shifts/:id/confirm", { preHandler: auth, schema: { tags: ["schedule"], params: { type: "object", required: ["id"], properties: { id: { type: "string", minLength: 1, maxLength: 128 } } }, response: { 200: RecurringShiftSchema, 404: ErrorEnvelopeSchema } } }, async (r) => d.commutes.confirm(r.identity!, r.params.id));
}
