import type { Firestore } from "firebase-admin/firestore";
import { Timestamp } from "firebase-admin/firestore";
import { RideError, type RideRequestRecord } from "./domain";
import type { RideStore } from "./ports";
const decode=(id:string,v:FirebaseFirestore.DocumentData):RideRequestRecord=>({...v,id,createdAt:v.createdAt.toDate(),crewAgreedAt:v.crewAgreedAt?.toDate()??null,captainDecidedAt:v.captainDecidedAt?.toDate()??null,confirmedAt:v.confirmedAt?.toDate()??null}as RideRequestRecord);
const pair=(tenant:string,a:string,b:string)=>`${tenant}_${[a,b].sort().join("_")}`;
export class FirestoreRideStore implements RideStore {
  constructor(private readonly db:Firestore){}
  private restrictionRefs(tenant:string,a:string,b:string){const c=this.db.collection("matchingRestrictions");return[c.doc(pair(tenant,a,b)),c.doc(`${tenant}_user_${a}`),c.doc(`${tenant}_user_${b}`)]as const;}
  private restricted(s:FirebaseFirestore.DocumentSnapshot[],now:Date){const active=(d:FirebaseFirestore.DocumentSnapshot)=>d.exists&&d.data()?.safetyRestricted===true&&d.data()?.restrictionThrough?.toDate()>now;return(s[0]?.exists&&s[0].data()?.blocked===true)||active(s[1]!)||active(s[2]!);}
  async create(v:RideRequestRecord){const r=this.db.collection("rideRequests").doc(v.id);await this.db.runTransaction(async tx=>{const old=await tx.get(r);if(old.exists)return;const restrictions=await tx.getAll(...this.restrictionRefs(v.tenantId,v.crewUid,v.captainUid));if(this.restricted(restrictions,v.createdAt))throw new RideError("Match selection is no longer available.","MATCH_RESTRICTED",409);tx.create(r,{...v,createdAt:Timestamp.fromDate(v.createdAt)});});return(await this.get(v.id))!;}
  async get(id:string){const s=await this.db.collection("rideRequests").doc(id).get();return s.exists?decode(s.id,s.data()!):null;}
  async listForParticipant(uid:string,limit:number){const[a,b]=await Promise.all([this.db.collection("rideRequests").where("crewUid","==",uid).limit(limit).get(),this.db.collection("rideRequests").where("captainUid","==",uid).limit(limit).get()]);const m=new Map<string,RideRequestRecord>();for(const d of[...a.docs,...b.docs])m.set(d.id,decode(d.id,d.data()));return[...m.values()].sort((x,y)=>y.createdAt.getTime()-x.createdAt.getTime()).slice(0,limit);}
  async listForTenant(t:string,w:string,from:Date,through:Date){const s=await this.db.collection("rideRequests").where("tenantId","==",t).where("worksiteId","==",w).where("createdAt",">=",Timestamp.fromDate(from)).where("createdAt","<=",Timestamp.fromDate(through)).get();return s.docs.map(d=>decode(d.id,d.data()));}
  async agree(id:string,uid:string,now:Date){const r=this.db.collection("rideRequests").doc(id);await this.db.runTransaction(async tx=>{const s=await tx.get(r);if(!s.exists||s.data()!.crewUid!==uid)throw new RideError("Ride request not found.","RIDE_NOT_FOUND",404);const v=decode(s.id,s.data()!);if(["pending_captain","confirmed"].includes(v.status))return;if(v.status!=="awaiting_crew_agreement")throw new RideError("Ride request cannot be agreed in its current state.","INVALID_RIDE_STATE",409);tx.update(r,{status:"pending_captain",crewAgreedAt:Timestamp.fromDate(now)});});return(await this.get(id))!;}
  async decide(id:string,uid:string,accepted:boolean,now:Date){const r=this.db.collection("rideRequests").doc(id);await this.db.runTransaction(async tx=>{const s=await tx.get(r);if(!s.exists||s.data()!.captainUid!==uid)throw new RideError("Ride request not found.","RIDE_NOT_FOUND",404);const v=decode(s.id,s.data()!);if((accepted&&v.status==="confirmed")||(!accepted&&v.status==="declined"))return;if(v.status!=="pending_captain"||!v.crewAgreedAt)throw new RideError("Crew agreement is required before the captain decision.","CREW_AGREEMENT_REQUIRED",409);if(!accepted)return void tx.update(r,{status:"declined",captainDecidedAt:Timestamp.fromDate(now)});const restrictions=await tx.getAll(...this.restrictionRefs(v.tenantId,v.crewUid,v.captainUid));if(this.restricted(restrictions,now))throw new RideError("This ride can no longer be accepted.","MATCH_RESTRICTED",409);const rr=this.db.collection("rideReservations").doc(`${v.captainUid}_${v.shiftId}_${v.leg}`),rs=await tx.get(rr),count=rs.data()?.count??0;if(count>=v.capacitySnapshot)throw new RideError("Captain capacity is no longer available.","CAPACITY_UNAVAILABLE",409);if(rs.exists)tx.update(rr,{count:count+1,updatedAt:Timestamp.fromDate(now)});else tx.create(rr,{count:1,captainUid:uid,updatedAt:Timestamp.fromDate(now)});tx.update(r,{status:"confirmed",captainDecidedAt:Timestamp.fromDate(now),confirmedAt:Timestamp.fromDate(now)});});return(await this.get(id))!;}
  async cancel(id:string,uid:string,reason:string,now:Date){const r=this.db.collection("rideRequests").doc(id);await this.db.runTransaction(async tx=>{const s=await tx.get(r);if(!s.exists||(s.data()!.crewUid!==uid&&s.data()!.captainUid!==uid))throw new RideError("Ride request not found.","RIDE_NOT_FOUND",404);const v=decode(s.id,s.data()!);if(v.status==="cancelled")return;if(v.status!=="confirmed")throw new RideError("Only a confirmed trip can be cancelled.","INVALID_RIDE_STATE",409);const rr=this.db.collection("rideReservations").doc(`${v.captainUid}_${v.shiftId}_${v.leg}`),rs=await tx.get(rr);if(rs.exists)tx.update(rr,{count:Math.max(0,(rs.data()?.count??1)-1),updatedAt:Timestamp.fromDate(now)});tx.update(r,{status:"cancelled",cancellationReason:reason,cancelledBy:uid,cancelledAt:Timestamp.fromDate(now)});});return(await this.get(id))!;}
}
