import assert from "node:assert/strict";
import test from "node:test";
import { buildApi } from "../src/app"; import type { ApiConfig } from "../src/config";
import { MemoryCommuteStore } from "../src/modules/commute/memory-store"; import { CommuteService } from "../src/modules/commute/service";
import { MemoryMembershipStore } from "../src/modules/membership/memory-store"; import type { FirebaseTokenVerifier } from "../src/modules/membership/ports"; import { MembershipService } from "../src/modules/membership/service";
const now = new Date("2026-08-12T14:00:00.000Z"); const config: ApiConfig = { environment: "test", host: "127.0.0.1", port: 4100, release: "commute-test", exposeDocumentation: false, referralCodePepper: "test-referral-pepper-value", firebase: { apiKey: null, authDomain: null, projectId: "test", appId: null } };
async function fixture() { const ms = new MemoryMembershipStore(); for (const uid of ["worker", "other"]) ms.memberships.set(uid, { id: uid, uid, email: `${uid}@example.test`, tenantId: uid === "worker" ? "tenant-a" : "tenant-b", worksiteId: uid === "worker" ? "site-a" : "site-b", role: "worker", status: "active", referralCodeId: "bootstrap", submittedAt: now }); const memberships = new MembershipService({ store: ms, referralPepper: config.referralCodePepper!, now: () => now }); const store = new MemoryCommuteStore(); const commutes = new CommuteService(store, () => now); const verifier: FirebaseTokenVerifier = { verifyIdToken: async (token) => ({ uid: token, email: `${token}@example.test`, email_verified: true }) }; const app = await buildApi({ config, logger: false, membership: { verifier, service: memberships }, commute: { verifier, memberships, commutes } }); return { app, store }; }
const auth = (uid = "worker") => ({ authorization: `Bearer ${uid}` });
test("profile enforces captain capacity and remains tenant-scoped", async () => { const { app, store } = await fixture(); try { const bad = await app.inject({ method: "PUT", url: "/v1/profile", headers: auth(), payload: { displayName: "Alex", adultConfirmed: true, toWorkRole: "captain", homeRole: "crew", maximumDetourMinutes: 15, seatsAvailable: 0, notificationsEnabled: true } }); assert.equal(bad.statusCode, 400); assert.equal(bad.json().error.code, "INVALID_CAPACITY"); const saved = await app.inject({ method: "PUT", url: "/v1/profile", headers: auth(), payload: { displayName: " Alex ", adultConfirmed: true, toWorkRole: "either", homeRole: "crew", maximumDetourMinutes: 15, seatsAvailable: 2, notificationsEnabled: true } }); assert.equal(saved.statusCode, 200); assert.equal(saved.json().displayName, "Alex"); store.profiles.set("other", { ...store.profiles.get("worker")!, uid: "other", tenantId: "tenant-a", worksiteId: "site-a" }); const hidden = await app.inject({ method: "GET", url: "/v1/profile", headers: auth("other") }); assert.equal(hidden.statusCode, 404); } finally { await app.close(); } });
test("manual recurring shifts validate zones and are confirmed", async () => { const { app } = await fixture(); try { const invalid = await app.inject({ method: "POST", url: "/v1/shifts", headers: auth(), payload: { weekdays: ["MO"], arrivalTime: "08:00", departureTime: "17:00", timeZone: "Mars/Olympus", effectiveFrom: "2026-08-17" } }); assert.equal(invalid.statusCode, 400); assert.equal(invalid.json().error.code, "INVALID_TIME_ZONE"); const saved = await app.inject({ method: "POST", url: "/v1/shifts", headers: auth(), payload: { weekdays: ["MO", "WE", "FR"], arrivalTime: "08:00", departureTime: "17:00", timeZone: "America/New_York", effectiveFrom: "2026-08-17" } }); assert.equal(saved.statusCode, 201); assert.equal(saved.json().status, "confirmed"); assert.equal(saved.json().source, "manual"); } finally { await app.close(); } });
test("ICS imports minimized candidate shifts that require confirmation", async () => { const { app, store } = await fixture(); try { const ics = ["BEGIN:VCALENDAR", "BEGIN:VEVENT", "SUMMARY:Private shift title is discarded", "DTSTART;TZID=America/New_York:20260817T080000", "DTEND;TZID=America/New_York:20260817T170000", "RRULE:FREQ=WEEKLY;BYDAY=MO,WE,FR", "END:VEVENT", "END:VCALENDAR"].join("\r\n"); const imported = await app.inject({ method: "POST", url: "/v1/schedule/ics", headers: auth(), payload: { ics } }); assert.equal(imported.statusCode, 201); assert.deepEqual(imported.json().shifts[0].weekdays, ["MO", "WE", "FR"]); assert.equal(imported.json().shifts[0].status, "candidate"); assert.equal(JSON.stringify([...store.shifts.values()]).includes("Private shift"), false); const id = imported.json().shifts[0].id; const denied = await app.inject({ method: "POST", url: `/v1/shifts/${id}/confirm`, headers: auth("other") }); assert.equal(denied.statusCode, 404); const confirmed = await app.inject({ method: "POST", url: `/v1/shifts/${id}/confirm`, headers: auth() }); assert.equal(confirmed.json().status, "confirmed"); } finally { await app.close(); } });
test("malformed and oversized event sets are rejected without partial writes", async () => { const { app, store } = await fixture(); try { const bad = await app.inject({ method: "POST", url: "/v1/schedule/ics", headers: auth(), payload: { ics: "BEGIN:VCALENDAR\nBEGIN:VEVENT\nDTSTART:20260817T080000\nEND:VEVENT\nEND:VCALENDAR" } }); assert.equal(bad.statusCode, 400); assert.equal(bad.json().error.code, "INVALID_ICS"); assert.equal(store.shifts.size, 0); } finally { await app.close(); } });
