import assert from "node:assert/strict";
import test from "node:test";
import type { RequestIdentity } from "../src/modules/membership/domain";
import { MemoryMatchingStore } from "../src/modules/matching/memory-store";
import { MemoryOperationsStore } from "../src/modules/operations/memory-store";
import { OperationsError } from "../src/modules/operations/domain";
import { OperationsService } from "../src/modules/operations/service";
const now=new Date("2026-08-13T12:00:00Z");
const moderator:RequestIdentity={uid:"mod",email:"mod@test",emailVerified:true,membershipId:"mod",tenantId:"tenant",worksiteId:"site",role:"moderator"};
const worker:RequestIdentity={...moderator,uid:"worker",membershipId:"worker",role:"worker"};
function fixture(){const store=new MemoryOperationsStore(),matches=new MemoryMatchingStore(),service=new OperationsService(store,()=>now,matches);return{store,matches,service};}
test("safety reports become tenant-scoped cases without exposing narratives in the queue",async()=>{const f=fixture();await f.service.captureSafetyReport({id:"case",tenantId:"tenant",worksiteId:"site",category:"unsafe_driving",subjectUid:"subject",reporterUid:"worker",narrative:"restricted details",createdAt:now});const result=await f.service.listCases(moderator);assert.equal(result.cases.length,1);assert.equal(result.cases[0]?.subjectUserId,"subject");assert.equal(JSON.stringify(result).includes("restricted details"),false);assert.equal((await f.service.listCases({...moderator,tenantId:"other"})).cases.length,0);});
test("assignment and decisions append audit evidence",async()=>{const f=fixture();await f.service.captureSafetyReport({id:"case",tenantId:"tenant",worksiteId:"site",category:"harassment",subjectUid:"subject",reporterUid:"worker",narrative:"restricted",createdAt:now});await f.service.assign(moderator,"case","Taking ownership");const decision=await f.service.decide(moderator,"case",{action:"no_action",reason:"Evidence did not substantiate the report"});assert.equal(decision.status,"closed");assert.deepEqual(f.store.audits.map(v=>v.action),["assigned","no_action"]);assert.equal(f.store.audits[1]?.reason,"Evidence did not substantiate the report");});
test("temporary restrictions require a subject and future expiry and are committed with the case",async()=>{const f=fixture();await f.service.captureSafetyReport({id:"case",tenantId:"tenant",worksiteId:"site",category:"unsafe_driving",subjectUid:"subject",reporterUid:"worker",narrative:"restricted",createdAt:now});await f.service.assign(moderator,"case","Taking ownership");await assert.rejects(()=>f.service.decide(moderator,"case",{action:"temporary_restriction",reason:"Review required"}),e=>e instanceof OperationsError&&e.code==="RESTRICTION_END_REQUIRED");await f.service.decide(moderator,"case",{action:"temporary_restriction",reason:"Safety review required",restrictionThrough:"2099-01-01T00:00:00.000Z"});assert.equal(f.store.restrictions.has("tenant:subject"),true);});
test("moderators cannot take over another assignee or decide without self-assignment",async()=>{const f=fixture();await f.service.captureSafetyReport({id:"case",tenantId:"tenant",worksiteId:"site",category:"harassment",subjectUid:"subject",reporterUid:"worker",narrative:"restricted",createdAt:now});await assert.rejects(()=>f.service.decide(moderator,"case",{action:"no_action",reason:"Not assigned"}),e=>e instanceof OperationsError&&e.code==="CASE_SELF_ASSIGNMENT_REQUIRED");await f.service.assign(moderator,"case","Taking ownership");await assert.rejects(()=>f.service.assign({...moderator,uid:"other-mod"},"case","Taking over"),e=>e instanceof OperationsError&&e.code==="CASE_ASSIGNED_TO_OTHER");});
test("concurrent decisions cannot overwrite a terminal decision",async()=>{const f=fixture();await f.service.captureSafetyReport({id:"case",tenantId:"tenant",worksiteId:"site",category:"harassment",subjectUid:"subject",reporterUid:"worker",narrative:"restricted",createdAt:now});await f.service.assign(moderator,"case","Taking ownership");const results=await Promise.allSettled([f.service.decide(moderator,"case",{action:"no_action",reason:"First result"}),f.service.decide(moderator,"case",{action:"close",reason:"Second result"})]);assert.equal(results.filter(v=>v.status==="fulfilled").length,1);assert.equal(f.store.audits.filter(v=>["no_action","close"].includes(v.action)).length,1);});
test("export and deletion requests are participant-scoped, idempotent, and disclose retention",async()=>{const f=fixture();const first=await f.service.request(worker,"export"),again=await f.service.request(worker,"export"),deletion=await f.service.request(worker,"deletion");assert.equal(first.id,again.id);assert.notEqual(first.id,deletion.id);assert.match(deletion.retentionNotice,/legal hold/);const list=await f.service.requests(worker);assert.equal(list.requests.length,2);assert.equal((await f.service.requests({...worker,uid:"other"})).requests.length,0);});
test("simultaneous privacy retries create one queued request",async()=>{const f=fixture();const values=await Promise.all(Array.from({length:20},()=>f.service.request(worker,"export")));assert.equal(new Set(values.map(v=>v.id)).size,1);assert.equal(f.store.requests.length,1);});
