import { randomUUID } from "node:crypto";
import type { DataRequestType, ModerationDecisionBody } from "../../../../../packages/contracts/src";
import type { MatchingStore } from "../matching/ports";
import type { RequestIdentity } from "../membership/domain";
import { OperationsError } from "./domain";
import type { OperationsStore } from "./ports";
const retentionNotice="Safety, audit, and legally required records may be retained under policy or legal hold.";
export class OperationsService {
  constructor(private readonly store:OperationsStore,private readonly now=()=>new Date(),private readonly matches?:MatchingStore){}
  async captureSafetyReport(v:{id:string;tenantId:string;worksiteId:string;category:string;subjectUid:string|null;reporterUid:string;narrative:string;createdAt:Date}){await this.store.createCase({...v,status:"open",assignedTo:null,updatedAt:v.createdAt});}
  async listCases(i:RequestIdentity){const cases=await this.store.listCases(i.tenantId,100);return{cases:cases.map(v=>({id:v.id,category:v.category,status:v.status,subjectUserId:v.subjectUid,assignedTo:v.assignedTo,createdAt:v.createdAt.toISOString(),updatedAt:v.updatedAt.toISOString()}))};}
  private async owned(i:RequestIdentity,id:string){const v=await this.store.getCase(id);if(!v||v.tenantId!==i.tenantId)throw new OperationsError("Moderation case not found.","CASE_NOT_FOUND",404);return v;}
  async assign(i:RequestIdentity,id:string,reason:string){const v=await this.owned(i,id),now=this.now();v.assignedTo=i.uid;v.status="assigned";v.updatedAt=now;await this.store.saveCase(v,{id:randomUUID(),caseId:id,tenantId:i.tenantId,actorUid:i.uid,action:"assigned",reason:reason.trim(),occurredAt:now});return{id:v.id,category:v.category,status:v.status,subjectUserId:v.subjectUid,assignedTo:v.assignedTo,createdAt:v.createdAt.toISOString(),updatedAt:v.updatedAt.toISOString()};}
  async decide(i:RequestIdentity,id:string,b:ModerationDecisionBody){const v=await this.owned(i,id),now=this.now();if(b.action==="temporary_restriction"&&!b.restrictionThrough)throw new OperationsError("A restriction end time is required.","RESTRICTION_END_REQUIRED",400);if(b.restrictionThrough&&new Date(b.restrictionThrough)<=now)throw new OperationsError("Restriction end time must be in the future.","INVALID_RESTRICTION_END",400);if(b.action==="temporary_restriction"){if(!v.subjectUid)throw new OperationsError("This case has no subject to restrict.","CASE_SUBJECT_REQUIRED",409);if(!this.matches)throw new OperationsError("Restriction processing is unavailable.","RESTRICTION_UNAVAILABLE",503);await this.matches.restrictUser(i.tenantId,v.subjectUid,new Date(b.restrictionThrough!),now);}v.status=b.action==="close"||b.action==="no_action"?"closed":"actioned";v.updatedAt=now;await this.store.saveCase(v,{id:randomUUID(),caseId:id,tenantId:i.tenantId,actorUid:i.uid,action:b.action,reason:b.reason.trim(),occurredAt:now});return{caseId:id,status:v.status as "actioned"|"closed",action:b.action,decidedAt:now.toISOString()};}
  private view(v:{id:string;type:DataRequestType;status:"queued";requestedAt:Date}){return{id:v.id,type:v.type,status:v.status,requestedAt:v.requestedAt.toISOString(),retentionNotice};}
  async request(i:RequestIdentity,type:DataRequestType){const existing=await this.store.findQueuedRequest(i.uid,type);if(existing)return this.view(existing);const v={id:randomUUID(),uid:i.uid,tenantId:i.tenantId,type,status:"queued" as const,requestedAt:this.now()};await this.store.createDataRequest(v);return this.view(v);}
  async requests(i:RequestIdentity){return{requests:(await this.store.listDataRequests(i.uid)).map(v=>this.view(v))};}
}
